# Generated by Django 3.1.1 on 2020-11-07 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='pvp',
        ),
    ]
