# Generated by Django 3.1.1 on 2020-11-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='select',
            field=models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=1),
        ),
    ]
