# Generated by Django 3.1.1 on 2020-11-02 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20201102_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='commpra',
            new_name='compra',
        ),
    ]
