# Generated by Django 3.1.1 on 2020-11-03 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0005_auto_20201031_1926'),
        ('inventario', '0004_auto_20201102_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='fecha_salida',
        ),
        migrations.AddField(
            model_name='inventario',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='venta.venta'),
        ),
    ]
