# Generated by Django 3.1.1 on 2020-11-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_auto_20201105_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_compra',
            name='p_compra_actual',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True),
        ),
    ]
