# Generated by Django 3.1.1 on 2020-10-30 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_venta',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='detalle_venta',
            name='cantidadp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detalle_venta',
            name='cantidads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detalle_venta',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='servicio.servicio'),
        ),
    ]
