# Generated by Django 3.1.1 on 2020-10-31 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_auto_20201030_0818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle_venta',
            old_name='subtotal',
            new_name='subtotalp',
        ),
        migrations.AddField(
            model_name='detalle_venta',
            name='subtotals',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
