# Generated by Django 3.1.1 on 2020-10-31 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
        ('venta', '0003_auto_20201031_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_venta',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producto.producto'),
        ),
    ]
