# Generated by Django 3.1.1 on 2020-11-01 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
        ('producto', '0001_initial'),
        ('venta', '0004_auto_20201031_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_venta',
            name='producto',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='producto.producto'),
        ),
        migrations.AlterField(
            model_name='detalle_venta',
            name='servicio',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='servicio.servicio'),
        ),
    ]
