# Generated by Django 3.1.1 on 2020-11-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='avatar',
            field=models.ImageField(default='empleado/admin.png', upload_to='empleado/%Y/%m/%d'),
        ),
    ]
